Update sample.yml

diff --git a/.github/workflows/sample.yml b/.github/workflows/sample.yml
--- a/.github/workflows/sample.yml
+++ b/.github/workflows/sample.yml
@@ -25,7 +25,7 @@ jobs:
         run: |
           if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
             echo "BRANCH_NAME=main" >> $GITHUB_ENV
-            else
+          else
             echo "Branch not permitted"
             exit 1
           fi
@@ -33,7 +33,7 @@ jobs:
       - name: Build Docker image
         run: |
           docker build -t gitactions-ecs:${{ env.BRANCH_NAME }}-${{ github.run_number }} .
-          docker tag gitactions-ecs:${{ env.BRANCH_NAME }}-${{ github.run_number }}468167146633.dkr.ecr.ap-south-1.amazonaws.com/mvgrepo:${{ env.BRANCH_NAME }}-${{ github.run_number }}
+          docker tag gitactions-ecs:${{ env.BRANCH_NAME }}-${{ github.run_number }} 468167146633.dkr.ecr.ap-south-1.amazonaws.com/mvgrepo:${{ env.BRANCH_NAME }}-${{ github.run_number }}
     
       - name: Login to Amazon ECR
         id: login-ecr
@@ -42,50 +42,50 @@ jobs:
       - name: Push Docker image to Amazon ECR
         run: |
           docker push 468167146633.dkr.ecr.ap-south-1.amazonaws.com/mvgrepo:${{ env.BRANCH_NAME }}-${{ github.run_number }}
+      
       - name: Deploy to ECS
         run: |
-             
-             startECSDeploy() {
-              # Command to create new td.
-               sed -e "s;GIT_COMMIT;${IMAGE_VERSION};g" ${JSON_FILE}.json > ${JSON_FILE}-new-${{ github.run_number }}.json
-               sed -e "s;task_role;${TASK_ROLE};g" ${JSON_FILE}-new-${{ github.run_number }}.json > ${JSON_FILE}-${{ github.run_number }}.json
-               cat ${JSON_FILE}-${{ github.run_number }}.json
+          startECSDeploy() {
+            # Command to create a new task definition.
+            sed -e "s;GIT_COMMIT;${IMAGE_VERSION};g" ${JSON_FILE}.json > ${JSON_FILE}-new-${{ github.run_number }}.json
+            sed -e "s;task_role;${TASK_ROLE};g" ${JSON_FILE}-new-${{ github.run_number }}.json > ${JSON_FILE}-${{ github.run_number }}.json
+            cat ${JSON_FILE}-${{ github.run_number }}.json
 
-              aws ecs register-task-definition --family ${TASK_FAMILY} --cli-input-json file://${JSON_FILE}-${{ github.run_number }}.json --region ap-south-1
+            aws ecs register-task-definition --family ${TASK_FAMILY} --cli-input-json file://${JSON_FILE}-${{ github.run_number }}.json --region ap-south-1
 
-             # Updating the service.
-             TASK_REVISION=$(aws ecs describe-task-definition --task-definition ${TASK_FAMILY} --region ap-south-1 --query "taskDefinition.revision" --output text)
-             echo $TASK_REVISION
-             DESIRED_COUNT=$(aws ecs describe-services --cluster ${CLUSTER} --services ${SERVICE_NAME} --region ap-south-1 --query "services[0].desiredCount" --output text)
-             echo $DESIRED_COUNT
+            # Updating the service.
+            TASK_REVISION=$(aws ecs describe-task-definition --task-definition ${TASK_FAMILY} --region ap-south-1 --query "taskDefinition.revision" --output text)
+            echo $TASK_REVISION
 
-             OLD_TASK_ID=$(aws ecs list-tasks --cluster ${CLUSTER} --desired-status RUNNING --family ${TASK_FAMILY} --region ap-south-1--query "taskArns[0]" --output text)
-             echo $OLD_TASK_ID
-            
+            DESIRED_COUNT=$(aws ecs describe-services --cluster ${CLUSTER} --services ${SERVICE_NAME} --region ap-south-1 --query "services[0].desiredCount" --output text)
+            echo $DESIRED_COUNT
 
-             aws ecs update-service --cluster ${CLUSTER} --service ${SERVICE_NAME} --desired-count ${RUNNING_COUNT} --task-definition ${TASK_FAMILY}:${TASK_REVISION} --force-new-deployment --region ap-south-1
+            OLD_TASK_ID=$(aws ecs list-tasks --cluster ${CLUSTER} --desired-status RUNNING --family ${TASK_FAMILY} --region ap-south-1 --query "taskArns[0]" --output text)
+            echo $OLD_TASK_ID
 
-             #Waiting for the service to be available in the cluster.
-             aws ecs wait services-stable --cluster ${CLUSTER} --services ${SERVICE_NAME} --region ap-south-1
+            aws ecs update-service --cluster ${CLUSTER} --service ${SERVICE_NAME} --desired-count ${RUNNING_COUNT} --task-definition ${TASK_FAMILY}:${TASK_REVISION} --force-new-deployment --region ap-south-1
 
-             if [ $? -eq 0 ]; then
-                echo "Build got deployed successfully"
-             else
-             echo "Build failed"
-             exit 1
-             fi
-             rm -rf ${JSON_FILE}-${{ github.run_number }}.json
-              }
+            #Waiting for the service to be available in the cluster.
+            aws ecs wait services-stable --cluster ${CLUSTER} --services ${SERVICE_NAME} --region ap-south-1
 
-             if [ "${{ github.ref }}" == "refs/heads/main" ]; then
-             SERVICE_NAME="MVGServicesdef"
-             IMAGE_VERSION="${{ env.BRANCH_NAME }}-${{ github.run_number }}"
-             TASK_FAMILY="TaskdefintionforMVG"
-             CLUSTER="MVGCluster"
-             TASK_ROLE="ecsTaskExecutionRole"
-             JSON_FILE=".github/workflows/task-definition"
-             RUNNING_COUNT=1
-             startECSDeploy
-             else
-                  echo "Skip deployment"
-             fi
+            if [ $? -eq 0 ]; then
+              echo "Build got deployed successfully"
+            else
+              echo "Build failed"
+              exit 1
+            fi
+            rm -rf ${JSON_FILE}-${{ github.run_number }}.json
+          }
+
+          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
+            SERVICE_NAME="MVGServicesdef"
+            IMAGE_VERSION="${{ env.BRANCH_NAME }}-${{ github.run_number }}"
+            TASK_FAMILY="TaskdefintionforMVG"
+            CLUSTER="MVGCluster"
+            TASK_ROLE="ecsTaskExecutionRole"
+            JSON_FILE=".github/workflows/task-definition"
+            RUNNING_COUNT=1
+            startECSDeploy
+          else
+            echo "Skip deployment"
+          fi
